import Link from "next/link";
type Kind="user"|"developer"|"sdk"|"api";
const nav={user:["What is Artery?","Key Concepts","Connect Your Wallet","First ARC Trade","Markets","Spot Trading","Orders","Fees","Wallet Security"],developer:["Introduction","Architecture","ARC Network","Argus Markets","Uniswap V4","Wallet Integration","Smart Contracts","Security"],sdk:["Quickstart","Installation","Market Client","Token Registry","Quote Client","Wallet Client","V4 Transactions","Examples"],api:["Overview","Authentication","Tokens","Markets","Quotes","Pools","Swaps","Rate Limits"]};
const title={user:"What is Artery?",developer:"Build on Artery",sdk:"Artery SDK",api:"Artery API Reference"};
export function DocsPage({kind}:{kind:Kind}){const items=nav[kind];return <><div className="docs-tabs"><Link className={kind==='user'?'on':''} href="/docs/user-docs/start">User Docs</Link><Link className={kind==='developer'?'on':''} href="/docs/developer-docs">Developer Docs</Link><Link className={kind==='sdk'?'on':''} href="/docs/sdk">SDK</Link><Link className={kind==='api'?'on':''} href="/docs/api">API Docs</Link></div><main className="docs-layout"><aside className="sidebar"><input className="search" placeholder="Search documentation"/><h4>{kind==='user'?'Start here':kind}</h4>{items.map((x,i)=><Link className={i===0?'active':''} href="#" key={x}>{x}</Link>)}</aside><article className="article"><p className="muted">Artery Docs / {kind}</p><h1>{title[kind]}</h1>{kind==='user'?<User/>:kind==='developer'?<Developer/>:kind==='sdk'?<SDK/>:<API/>}</article></main></>}
function User(){return <><p>Artery is a decentralized market interface built for ARC. It provides one workspace to discover Argus-launched tokens, inspect activity, and access Uniswap V4 liquidity with a connected wallet.</p><div className="card doc-card"><b>ARC-native markets</b><p>Artery focuses on real Argus token contracts and ARC mainnet V4 pools.</p></div><h2>Core features</h2><ul><li>Browse Argus V4 token pairs and current ARC activity.</li><li>Open a dedicated trading terminal for every supported token.</li><li>Connect an EVM wallet and keep approval control.</li><li>Use USDC, ARC, WETH, and cirBTC quote assets.</li></ul><h2>Connect and trade</h2><p>Connect MetaMask, Rabby, Coinbase Wallet, or WalletConnect, switch to ARC Mainnet, select a market, and approve the transaction from your wallet.</p><h2>ARC network</h2><div className="card doc-card"><b>ARC Mainnet</b><p>Chain ID 5042 · RPC rpc.mainnet.arc.io · Explorer explorer.arc.io</p></div></>}
function Developer(){return <><p>Build ARC applications around Artery market discovery and Argus V4 execution.</p><h2>Architecture</h2><p>Token metadata comes from the Argus ecosystem. Pool state and settlement live on ARC. The interface never requires a custodial trading account.</p><h2>Contracts</h2><div className="card doc-card"><b>Uniswap V4 on ARC</b><p>PoolManager: 0x8366a39c… · Universal Router: 0x4fca4a51… · Permit2: 0x000000000022…</p></div><h2>Execution flow</h2><ol><li>Resolve the Argus token and V4 pool key.</li><li>Read ARC pool state and estimate output.</li><li>Approve Permit2 where required.</li><li>Submit the wallet-signed V4 router transaction.</li></ol></>}
function SDK(){return <><p>The Artery SDK exposes typed helpers for market discovery, ARC network configuration, quote formatting, and V4 transaction preparation.</p><h2>Install</h2><pre className="doc-code">npm install @artery/arc-sdk</pre><h2>Quickstart</h2><pre className="doc-code">{`import { ArteryClient } from "@artery/arc-sdk";\nconst client = new ArteryClient({ chainId: 5042 });\nconst markets = await client.markets.list();`}</pre><h2>Modules</h2><ul><li>Market and token registry</li><li>Pool-key resolution</li><li>ARC quote client</li><li>Wallet and Permit2 helpers</li></ul></>}
function API(){return <><p>Read normalized ARC market data for Artery interfaces and trading tools.</p><h2>Markets</h2><pre className="doc-code">GET /v1/markets</pre><h2>Token</h2><pre className="doc-code">GET /v1/tokens/:address</pre><h2>Quote</h2><pre className="doc-code">GET /v1/quote?tokenIn=USDC&amp;tokenOut=0x…&amp;amount=100</pre><div className="card doc-card"><b>Response policy</b><p>Prices are executable estimates, not guarantees. Requote immediately before submitting a transaction.</p></div></>}
